### ISSUE TITLE
Heroku-orgs using API v2 endpoint for the leave command

### ISSUE THREAD

**Issue by dmcinnes** [heroku/heroku-orgs#64]
I just found this one! Otherwise I think we're all good:

https://github.com/heroku/heroku-orgs/blob/68a6cf54b0f4a9f593f1c4c0f54a735191c8e372/commands/apps/leave.js#L12

/cc @raulb

**Comment by raulb** [comment]
Future me: Use `DELETE /organizations/apps/{app_id_or_name}/collaborators/{collaborator_id_or_email}` instead.

**Comment by raulb** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qpW3eKPo&#x2F;415-move-leave-off-v2-in-the-cli"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Move &#x2F;leave off v2 in the CLI</a>

**Comment by raulb** [comment]
@dmcinnes fixed by https://github.com/heroku/heroku-orgs/commit/b6787e3a2c51cde31344561356ed410ba231ba56.

Only question I have is, do I really need to use `DELETE /organizations/apps/{app_id_or_name}/collaborators/{collaborator_id_or_email} vs`DELETE /apps/{app_id_or_name}/collaborators/{collaborator_id_or_email}` depending on whether it is an org app or not?

**Comment by dmcinnes** [comment]
@raulb You're right! I completely forgot, `DELETE /apps/{app_id_or_name}/collaborators/{collaborator_id_or_email}` also supports deleting collaborators on org apps.

**Comment by raulb** [comment]
@dmcinnes sweet. I'll update the code (1 less API call!)
